name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - traitlets
  - IPython
  - requests
  - json
  - geopandas
  - more_itertools
  - matplotlib.pyplot
  - IPython.display
